--MySQL Solution
--First, write a SELECT query to get the name of the review that has the highest reviews
--This can be done by using COUNT() function along with group by. Order by this value DESCENDING and the name ASCENDING
